#!/usr/bin/bash

LINUX="Linux"
THING="la figa"

while test $# -gt 0; do
        case "$1" in
                -h|--help)
                    echo "-os           Replace Linux with current OS"
                    echo "-w            Replace Figa with Windows"
                    echo "-t  <thing>   Replace Figa with <thing>"
                    exit
                    ;;
                -os|--os)
                    LINUX=$(lsb_release -i | cut -f 2-)
                    shift
                    ;;
                -w|--windows)
                    THING="Windows"
                    shift
                    ;;
                -t|--thing)
                    THING=$2
                    shift 2
                    ;;
                *)
                    break
                    ;;
        esac
done

echo "Che schifo $THING."
echo "Meglio $LINUX!"